import type { PerfReport } from '../types';
import {
  SCORE_GOOD_THRESHOLD,
  SCORE_WARNING_THRESHOLD,
  MS_PER_SECOND,
} from '../types';
import { generateChartData } from './chartRenderer';

export function generateHtmlReport(report: PerfReport): string {
  const chartData = generateChartData(report);
  const duration = ((report.endTime - report.startTime) / MS_PER_SECOND).toFixed(1);

  const scoreColor =
    report.score >= SCORE_GOOD_THRESHOLD ? '#10b981' : report.score >= SCORE_WARNING_THRESHOLD ? '#f59e0b' : '#ef4444';
  const scoreLabel =
    report.score >= SCORE_GOOD_THRESHOLD ? 'GOOD' : report.score >= SCORE_WARNING_THRESHOLD ? 'WARNING' : 'POOR';

  const eventsJson = JSON.stringify(chartData.events);
  const stepsJson = JSON.stringify(chartData.steps);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>rn-perf-score Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }
  .container { max-width: 1200px; margin: 0 auto; }
  h1 { font-size: 24px; margin-bottom: 8px; color: #f8fafc; }
  .subtitle { color: #94a3b8; font-size: 14px; margin-bottom: 24px; }
  .score-card { display: flex; align-items: center; gap: 24px; background: #1e293b; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
  .score-value { font-size: 64px; font-weight: 800; line-height: 1; }
  .score-label { font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
  .score-details { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 16px; flex: 1; }
  .detail { background: #0f172a; border-radius: 8px; padding: 12px; }
  .detail-label { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; }
  .detail-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
  .chart-wrapper { position: relative; background: #1e293b; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
  .chart-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; }
  .chart-area { position: relative; }
  canvas { width: 100%; display: block; }
  #tooltip {
    display: none; position: absolute; pointer-events: none;
    background: #0f172aee; border: 1px solid #334155; border-radius: 8px;
    padding: 10px 14px; font-size: 12px; line-height: 1.6;
    white-space: nowrap; z-index: 10; backdrop-filter: blur(4px);
  }
  #tooltip .tt-time { color: #94a3b8; font-size: 11px; margin-bottom: 4px; }
  #tooltip .tt-js { color: #3b82f6; }
  #tooltip .tt-ui { color: #10b981; }
  #tooltip .tt-event { margin-top: 6px; padding-top: 6px; border-top: 1px solid #334155; }
  #tooltip .tt-event-item { font-size: 11px; }
  #crosshair { display: none; position: absolute; top: 0; width: 1px; background: #475569; pointer-events: none; z-index: 5; }
  .footer { text-align: center; color: #64748b; font-size: 12px; margin-top: 24px; }
</style>
</head>
<body>
<div class="container">
  <h1>rn-perf-score Report</h1>
  <p class="subtitle">${report.deviceInfo.platform} &middot; ${report.deviceInfo.model} &middot; ${duration}s &middot; ${new Date(report.startTime).toLocaleString()}</p>

  <div class="score-card">
    <div>
      <div class="score-value" style="color: ${scoreColor}">${report.score}</div>
      <div class="score-label" style="color: ${scoreColor}">${scoreLabel}</div>
    </div>
    <div class="score-details">
      <div class="detail">
        <div class="detail-label">JS Thread Avg</div>
        <div class="detail-value">${report.avgJsFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">UI Thread Avg</div>
        <div class="detail-value">${report.avgUiFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">JS Min</div>
        <div class="detail-value">${report.minJsFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">UI Min</div>
        <div class="detail-value">${report.minUiFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">Dropped (JS)</div>
        <div class="detail-value">${report.droppedFramesJs}</div>
      </div>
      <div class="detail">
        <div class="detail-label">Dropped (UI)</div>
        <div class="detail-value">${report.droppedFramesUi}</div>
      </div>
    </div>
  </div>

  <div class="chart-wrapper">
    <div class="chart-title">FPS Over Time</div>
    <div class="chart-area">
      <canvas id="fpsChart"></canvas>
      <div id="crosshair"></div>
      <div id="tooltip"></div>
    </div>
  </div>

  <div class="footer">Generated by rn-perf-score v${report.version}</div>
</div>

<script>
var timestamps = ${JSON.stringify(chartData.timestamps)};
var jsFps = ${JSON.stringify(chartData.jsFps)};
var uiFps = ${JSON.stringify(chartData.uiFps)};
var events = ${eventsJson};
var steps = ${stepsJson};
var targetFps = ${report.targetFps};

// Merge all markers (events + steps) into one sorted array for the timeline
var allMarkers = events.map(function(e) { return { t: e.timestamp, type: e.type, label: e.label }; })
  .concat(steps.map(function(s) { return { t: s.timestamp, type: 'step', label: s.label }; }))
  .sort(function(a, b) { return a.t - b.t; });

// Chart layout constants — shared between draw and hover
var CHART_H = 500;
var padding = { top: 20, right: 20, bottom: 180, left: 50 };
var maxTime, maxFps, chartW, chartH, canvasW;

function getEventColor(type) {
  var colors = {
    navigation: '#3b82f6',
    network_start: '#f59e0b',
    network_end: '#10b981',
    long_task: '#ef4444',
    custom: '#8b5cf6',
    step: '#c4b5fd'
  };
  return colors[type] || '#6b7280';
}

function xPos(t) { return padding.left + (t / maxTime) * chartW; }
function yPos(fps) { return padding.top + chartH - (fps / maxFps) * chartH; }
function tFromX(x) { return ((x - padding.left) / chartW) * maxTime; }

function drawChart() {
  var canvas = document.getElementById('fpsChart');
  var ctx = canvas.getContext('2d');
  var dpr = window.devicePixelRatio || 1;

  var rect = canvas.parentElement.getBoundingClientRect();
  canvasW = rect.width;
  canvas.width = canvasW * dpr;
  canvas.height = CHART_H * dpr;
  canvas.style.height = CHART_H + 'px';
  ctx.scale(dpr, dpr);

  chartW = canvasW - padding.left - padding.right;
  chartH = CHART_H - padding.top - padding.bottom;
  maxTime = Math.max.apply(null, timestamps.concat([1]));
  maxFps = targetFps + 5;

  // Background
  ctx.fillStyle = '#1e293b';
  ctx.fillRect(0, 0, canvasW, CHART_H);

  // Grid lines
  ctx.strokeStyle = '#334155';
  ctx.lineWidth = 0.5;
  for (var fps = 0; fps <= maxFps; fps += 15) {
    ctx.beginPath();
    ctx.moveTo(padding.left, yPos(fps));
    ctx.lineTo(canvasW - padding.right, yPos(fps));
    ctx.stroke();
    ctx.fillStyle = '#64748b';
    ctx.font = '11px sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText(fps + ' fps', padding.left - 8, yPos(fps) + 4);
  }

  // Time labels on x-axis
  var timeStep = Math.max(1, Math.ceil(maxTime / 10));
  for (var t = 0; t <= maxTime; t += timeStep) {
    ctx.fillStyle = '#64748b';
    ctx.font = '11px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(t.toFixed(0) + 's', xPos(t), CHART_H - padding.bottom + 18);
  }

  // Draw marker vertical lines + bottom labels
  var labelSlots = []; // track label positions to avoid overlap
  allMarkers.forEach(function(m) {
    var x = xPos(m.t);
    var color = getEventColor(m.type);

    // Vertical line
    ctx.strokeStyle = color + '50';
    ctx.lineWidth = 1;
    ctx.setLineDash([3, 3]);
    ctx.beginPath();
    ctx.moveTo(x, padding.top);
    ctx.lineTo(x, CHART_H - padding.bottom);
    ctx.stroke();
    ctx.setLineDash([]);

    // Small diamond marker at top
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.moveTo(x, padding.top - 2);
    ctx.lineTo(x + 4, padding.top + 3);
    ctx.lineTo(x, padding.top + 8);
    ctx.lineTo(x - 4, padding.top + 3);
    ctx.closePath();
    ctx.fill();

    // Rotated label at bottom — skip if too close to previous
    var tooClose = labelSlots.some(function(lx) { return Math.abs(lx - x) < 40; });
    if (!tooClose) {
      labelSlots.push(x);
      ctx.save();
      ctx.translate(x, CHART_H - padding.bottom + 28);
      ctx.rotate(-Math.PI / 4);
      ctx.fillStyle = color + 'cc';
      ctx.font = '10px sans-serif';
      ctx.textAlign = 'right';
      ctx.fillText(m.label, 0, 0);
      ctx.restore();
    }
  });

  // Area fills (draw before lines so lines are on top)
  drawArea(ctx, timestamps, jsFps, '#3b82f6');
  drawArea(ctx, timestamps, uiFps, '#10b981');

  // FPS lines
  drawLine(ctx, timestamps, jsFps, '#3b82f6');
  drawLine(ctx, timestamps, uiFps, '#10b981');

  // Legend (top right)
  var lx = canvasW - padding.right - 180;
  var ly = padding.top + 8;
  ctx.fillStyle = '#1e293b99';
  ctx.fillRect(lx - 8, ly - 8, 188, 28);

  ctx.fillStyle = '#3b82f6';
  ctx.fillRect(lx, ly, 12, 3);
  ctx.fillStyle = '#94a3b8';
  ctx.font = '11px sans-serif';
  ctx.textAlign = 'left';
  ctx.fillText('JS Thread', lx + 18, ly + 4);

  ctx.fillStyle = '#10b981';
  ctx.fillRect(lx + 90, ly, 12, 3);
  ctx.fillStyle = '#94a3b8';
  ctx.fillText('UI Thread', lx + 108, ly + 4);
}

function drawLine(ctx, xs, ys, color) {
  if (xs.length === 0) return;
  ctx.strokeStyle = color;
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(xPos(xs[0]), yPos(ys[0]));
  for (var i = 1; i < xs.length; i++) {
    ctx.lineTo(xPos(xs[i]), yPos(ys[i]));
  }
  ctx.stroke();
}

function drawArea(ctx, xs, ys, color) {
  if (xs.length === 0) return;
  ctx.fillStyle = color + '12';
  ctx.beginPath();
  ctx.moveTo(xPos(xs[0]), yPos(0));
  for (var i = 0; i < xs.length; i++) {
    ctx.lineTo(xPos(xs[i]), yPos(ys[i]));
  }
  ctx.lineTo(xPos(xs[xs.length - 1]), yPos(0));
  ctx.closePath();
  ctx.fill();
}

// Find nearest sample index for a given time
function nearestSample(t) {
  var best = 0;
  var bestDist = Infinity;
  for (var i = 0; i < timestamps.length; i++) {
    var d = Math.abs(timestamps[i] - t);
    if (d < bestDist) { bestDist = d; best = i; }
  }
  return best;
}

// Hover interaction
function setupHover() {
  var canvas = document.getElementById('fpsChart');
  var tooltip = document.getElementById('tooltip');
  var crosshair = document.getElementById('crosshair');
  var chartArea = canvas.parentElement;

  canvas.addEventListener('mousemove', function(e) {
    var rect = canvas.getBoundingClientRect();
    var mx = e.clientX - rect.left;
    var my = e.clientY - rect.top;

    // Only show tooltip when inside chart area
    if (mx < padding.left || mx > canvasW - padding.right ||
        my < padding.top || my > CHART_H - padding.bottom) {
      tooltip.style.display = 'none';
      crosshair.style.display = 'none';
      return;
    }

    var t = tFromX(mx);
    var idx = nearestSample(t);

    // Crosshair
    crosshair.style.display = 'block';
    crosshair.style.left = xPos(timestamps[idx]) + 'px';
    crosshair.style.top = padding.top + 'px';
    crosshair.style.height = chartH + 'px';

    // Build tooltip content
    var html = '<div class="tt-time">' + timestamps[idx].toFixed(2) + 's</div>';
    html += '<div class="tt-js">JS: <b>' + jsFps[idx] + '</b> fps</div>';
    html += '<div class="tt-ui">UI: <b>' + uiFps[idx] + '</b> fps</div>';

    // Find events near this timestamp (within 0.15s)
    var nearby = allMarkers.filter(function(m) {
      return Math.abs(m.t - timestamps[idx]) < 0.15;
    });
    if (nearby.length > 0) {
      html += '<div class="tt-event">';
      nearby.forEach(function(m) {
        var color = getEventColor(m.type);
        html += '<div class="tt-event-item" style="color:' + color + '">' + m.label + '</div>';
      });
      html += '</div>';
    }

    tooltip.innerHTML = html;
    tooltip.style.display = 'block';

    // Position tooltip — flip sides if near edge
    var tx = xPos(timestamps[idx]) + 16;
    var tw = tooltip.offsetWidth;
    if (tx + tw > canvasW - 10) {
      tx = xPos(timestamps[idx]) - tw - 16;
    }
    var ty = my - 20;
    if (ty < 0) ty = 0;
    if (ty + tooltip.offsetHeight > CHART_H) {
      ty = CHART_H - tooltip.offsetHeight;
    }
    tooltip.style.left = tx + 'px';
    tooltip.style.top = ty + 'px';
  });

  canvas.addEventListener('mouseleave', function() {
    tooltip.style.display = 'none';
    crosshair.style.display = 'none';
  });
}

drawChart();
setupHover();
window.addEventListener('resize', function() { drawChart(); });
</script>
</body>
</html>`;
}
