import type { PerfReport } from '../types';
import {
  SCORE_GOOD_THRESHOLD,
  SCORE_WARNING_THRESHOLD,
  MS_PER_SECOND,
} from '../types';
import { generateChartData } from './chartRenderer';

export function generateHtmlReport(report: PerfReport): string {
  const chartData = generateChartData(report);
  const duration = ((report.endTime - report.startTime) / MS_PER_SECOND).toFixed(1);

  const scoreColor =
    report.score >= SCORE_GOOD_THRESHOLD ? '#10b981' : report.score >= SCORE_WARNING_THRESHOLD ? '#f59e0b' : '#ef4444';
  const scoreLabel =
    report.score >= SCORE_GOOD_THRESHOLD ? 'GOOD' : report.score >= SCORE_WARNING_THRESHOLD ? 'WARNING' : 'POOR';

  const eventsJson = JSON.stringify(chartData.events);
  const stepsJson = JSON.stringify(chartData.steps);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>rn-perf-score Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 24px; }
  .container { max-width: 1200px; margin: 0 auto; }
  h1 { font-size: 24px; margin-bottom: 8px; color: #f8fafc; }
  .subtitle { color: #94a3b8; font-size: 14px; margin-bottom: 24px; }
  .score-card { display: flex; align-items: center; gap: 24px; background: #1e293b; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
  .score-value { font-size: 64px; font-weight: 800; line-height: 1; }
  .score-label { font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
  .score-details { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 16px; flex: 1; }
  .detail { background: #0f172a; border-radius: 8px; padding: 12px; }
  .detail-label { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; }
  .detail-value { font-size: 20px; font-weight: 700; margin-top: 4px; }
  .chart-container { background: #1e293b; border-radius: 12px; padding: 24px; margin-bottom: 24px; }
  .chart-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; }
  canvas { width: 100%; }
  .events-table { background: #1e293b; border-radius: 12px; padding: 24px; }
  .events-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; padding: 8px 12px; border-bottom: 1px solid #334155; }
  td { padding: 8px 12px; border-bottom: 1px solid #1e293b; font-size: 13px; }
  .event-type { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .footer { text-align: center; color: #64748b; font-size: 12px; margin-top: 24px; }
</style>
</head>
<body>
<div class="container">
  <h1>rn-perf-score Report</h1>
  <p class="subtitle">${report.deviceInfo.platform} &middot; ${report.deviceInfo.model} &middot; ${duration}s &middot; ${new Date(report.startTime).toLocaleString()}</p>

  <div class="score-card">
    <div>
      <div class="score-value" style="color: ${scoreColor}">${report.score}</div>
      <div class="score-label" style="color: ${scoreColor}">${scoreLabel}</div>
    </div>
    <div class="score-details">
      <div class="detail">
        <div class="detail-label">JS Thread Avg</div>
        <div class="detail-value">${report.avgJsFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">UI Thread Avg</div>
        <div class="detail-value">${report.avgUiFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">JS Min</div>
        <div class="detail-value">${report.minJsFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">UI Min</div>
        <div class="detail-value">${report.minUiFps} fps</div>
      </div>
      <div class="detail">
        <div class="detail-label">Dropped (JS)</div>
        <div class="detail-value">${report.droppedFramesJs}</div>
      </div>
      <div class="detail">
        <div class="detail-label">Dropped (UI)</div>
        <div class="detail-value">${report.droppedFramesUi}</div>
      </div>
    </div>
  </div>

  <div class="chart-container">
    <div class="chart-title">FPS Over Time</div>
    <canvas id="fpsChart" height="300"></canvas>
  </div>

  <div class="events-table" id="eventsSection">
    <div class="events-title">Event Timeline</div>
    <table>
      <thead>
        <tr><th>Time</th><th>Type</th><th>Label</th></tr>
      </thead>
      <tbody id="eventsBody"></tbody>
    </table>
  </div>

  <div class="footer">Generated by rn-perf-score v${report.version}</div>
</div>

<script>
// Data
const timestamps = ${JSON.stringify(chartData.timestamps)};
const jsFps = ${JSON.stringify(chartData.jsFps)};
const uiFps = ${JSON.stringify(chartData.uiFps)};
const events = ${eventsJson};
const steps = ${stepsJson};
const targetFps = ${report.targetFps};

// Draw chart using Canvas 2D (no external dependency)
function drawChart() {
  const canvas = document.getElementById('fpsChart');
  const ctx = canvas.getContext('2d');
  const dpr = window.devicePixelRatio || 1;

  const rect = canvas.getBoundingClientRect();
  canvas.width = rect.width * dpr;
  canvas.height = 300 * dpr;
  ctx.scale(dpr, dpr);

  const w = rect.width;
  const h = 300;
  const padding = { top: 20, right: 20, bottom: 60, left: 50 };
  const chartW = w - padding.left - padding.right;
  const chartH = h - padding.top - padding.bottom;

  const maxTime = Math.max(...timestamps, 1);
  const maxFps = targetFps + 5;

  function xPos(t) { return padding.left + (t / maxTime) * chartW; }
  function yPos(fps) { return padding.top + chartH - (fps / maxFps) * chartH; }

  // Background
  ctx.fillStyle = '#1e293b';
  ctx.fillRect(0, 0, w, h);

  // Grid lines
  ctx.strokeStyle = '#334155';
  ctx.lineWidth = 0.5;
  for (let fps = 0; fps <= maxFps; fps += 15) {
    ctx.beginPath();
    ctx.moveTo(padding.left, yPos(fps));
    ctx.lineTo(w - padding.right, yPos(fps));
    ctx.stroke();
    ctx.fillStyle = '#64748b';
    ctx.font = '11px sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText(fps + '', padding.left - 8, yPos(fps) + 4);
  }

  // Time labels
  const timeStep = Math.max(1, Math.ceil(maxTime / 10));
  for (let t = 0; t <= maxTime; t += timeStep) {
    ctx.fillStyle = '#64748b';
    ctx.font = '11px sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText(t.toFixed(0) + 's', xPos(t), h - padding.bottom + 20);
  }

  // Step markers (vertical lines + labels)
  steps.forEach(function(step) {
    const x = xPos(step.timestamp);
    ctx.strokeStyle = '#8b5cf680';
    ctx.lineWidth = 1;
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(x, padding.top);
    ctx.lineTo(x, h - padding.bottom);
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.save();
    ctx.translate(x, h - padding.bottom + 35);
    ctx.rotate(-Math.PI / 6);
    ctx.fillStyle = '#c4b5fd';
    ctx.font = '10px sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText(step.label, 0, 0);
    ctx.restore();
  });

  // Event markers
  events.forEach(function(evt) {
    const x = xPos(evt.timestamp);
    ctx.strokeStyle = getEventColor(evt.type) + '60';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(x, padding.top);
    ctx.lineTo(x, h - padding.bottom);
    ctx.stroke();
  });

  // Draw JS FPS line
  drawLine(ctx, timestamps, jsFps, '#3b82f6', xPos, yPos);

  // Draw UI FPS line
  drawLine(ctx, timestamps, uiFps, '#10b981', xPos, yPos);

  // Legend
  ctx.fillStyle = '#3b82f6';
  ctx.fillRect(padding.left, h - 15, 12, 3);
  ctx.fillStyle = '#94a3b8';
  ctx.font = '11px sans-serif';
  ctx.textAlign = 'left';
  ctx.fillText('JS Thread', padding.left + 18, h - 11);

  ctx.fillStyle = '#10b981';
  ctx.fillRect(padding.left + 100, h - 15, 12, 3);
  ctx.fillStyle = '#94a3b8';
  ctx.fillText('UI Thread', padding.left + 118, h - 11);
}

function drawLine(ctx, xs, ys, color, xPos, yPos) {
  if (xs.length === 0) return;
  ctx.strokeStyle = color;
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(xPos(xs[0]), yPos(ys[0]));
  for (let i = 1; i < xs.length; i++) {
    ctx.lineTo(xPos(xs[i]), yPos(ys[i]));
  }
  ctx.stroke();

  // Area fill
  ctx.fillStyle = color + '15';
  ctx.beginPath();
  ctx.moveTo(xPos(xs[0]), yPos(0));
  for (let i = 0; i < xs.length; i++) {
    ctx.lineTo(xPos(xs[i]), yPos(ys[i]));
  }
  ctx.lineTo(xPos(xs[xs.length - 1]), yPos(0));
  ctx.closePath();
  ctx.fill();
}

function getEventColor(type) {
  var colors = {
    navigation: '#3b82f6',
    network_start: '#f59e0b',
    network_end: '#10b981',
    long_task: '#ef4444',
    custom: '#8b5cf6'
  };
  return colors[type] || '#6b7280';
}

// Populate events table
function populateEvents() {
  var tbody = document.getElementById('eventsBody');
  var allEvents = events.map(function(e) { return { time: e.timestamp, type: e.type, label: e.label }; })
    .concat(steps.map(function(s) { return { time: s.timestamp, type: 'step', label: s.label }; }))
    .sort(function(a, b) { return a.time - b.time; });

  if (allEvents.length === 0) {
    document.getElementById('eventsSection').style.display = 'none';
    return;
  }

  allEvents.forEach(function(evt) {
    var tr = document.createElement('tr');
    var color = evt.type === 'step' ? '#c4b5fd' : getEventColor(evt.type);
    tr.innerHTML = '<td>' + evt.time.toFixed(2) + 's</td>'
      + '<td><span class="event-type" style="background:' + color + '20;color:' + color + '">' + evt.type + '</span></td>'
      + '<td>' + evt.label + '</td>';
    tbody.appendChild(tr);
  });
}

drawChart();
populateEvents();
window.addEventListener('resize', drawChart);
</script>
</body>
</html>`;
}
